"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var EquipmentTaxonomyController_1 = require("../controllers/EquipmentTaxonomyController");
var router = (0, express_1.Router)();
var Taxonomy = new EquipmentTaxonomyController_1.TaxonomyController();
router.get('/', function (req, res) { return Taxonomy.getAll(req, res); });
router.get('/:id', function (req, res) { return Taxonomy.getById(req, res); });
router.post('/', function (req, res) { return Taxonomy.create(req, res); });
router.put('/:id', function (req, res) { return Taxonomy.update(req, res); });
router.delete('/:id', function (req, res) { return Taxonomy.delete(req, res); });
exports.default = router;
